Repository AY2122S2-CS2103T-T11-4/tp, pull requests merged in 2022-04, with the labels that each got.

#125 Make GUI reflect outstanding salary and jobs that can be finalised
  build.gradle
  docs/images/Ui.png
  src/main/java/peoplesoft/MainApp.java
  src/main/java/peoplesoft/commons/core/GuiSettings.java
  src/main/java/peoplesoft/commons/core/Messages.java
  src/main/java/peoplesoft/logic/commands/ExportCommand.java
  src/main/java/peoplesoft/logic/export/Exporter.java
  src/main/java/peoplesoft/ui/regions/JobCard.java
  src/main/java/peoplesoft/ui/regions/PersonCard.java
  src/main/resources/view/JobListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OverviewPage.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#140 Fix `EditCommand` not working with `Rate`
  src/main/java/peoplesoft/logic/commands/EditCommand.java
Labels: type.Bug, severity.Medium

#200 UG fixes: low hanging fruit
  docs/UserGuide.md
Labels: type.UG

#204 Minor bug fixes for v1.4
  docs/UserGuide.md
  src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobFinalizeCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobMarkCommand.java
  src/main/java/peoplesoft/logic/parser/ParserUtil.java
  src/main/java/peoplesoft/model/job/Job.java
  src/main/java/peoplesoft/model/money/Rate.java
  src/test/java/peoplesoft/logic/parser/ParserUtilTest.java
Labels: priority.High

#202 Update Ian's PPP
  docs/images/ian_sketches.jpg
  docs/team/ian-from-dover.md
  src/main/java/peoplesoft/logic/commands/person/PersonDeleteCommand.java
Labels: type.Task, effort.Medium
