Repository AY2122S2-CS2103T-T11-4/tp, pull requests merged in 2022-03, with the labels that each got.

#31 Add Ian's PPP and User Image
  docs/images/ian-from-dover.png
  docs/team/ian-from-dover.md
Labels: priority.High

#46 Add Job class and Money class
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/Money.java
  src/test/java/seedu/address/model/job/JobTest.java
  src/test/java/seedu/address/model/job/MoneyTest.java
Labels: priority.High

#77 HelpWindow: Make Copy URL open directly in browser AND Fix git hook on Mac
  .githooks/pre-commit
  src/main/java/peoplesoft/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Medium

#65 Refactor JSON serdes
  src/main/java/peoplesoft/commons/util/JsonUtil.java
  src/main/java/peoplesoft/model/AddressBook.java
  src/main/java/peoplesoft/model/job/Money.java
  src/main/java/peoplesoft/model/job/Rate.java
  src/main/java/peoplesoft/model/person/Address.java
  src/main/java/peoplesoft/model/person/Email.java
  src/main/java/peoplesoft/model/person/Name.java
  src/main/java/peoplesoft/model/person/Person.java
  src/main/java/peoplesoft/model/person/Phone.java
  src/main/java/peoplesoft/model/person/UniquePersonList.java
  src/main/java/peoplesoft/model/tag/Tag.java
  src/main/java/peoplesoft/storage/JsonAdaptedPerson.java
  src/main/java/peoplesoft/storage/JsonAdaptedTag.java
  src/main/java/peoplesoft/storage/JsonAddressBookStorage.java
  src/main/java/peoplesoft/storage/JsonSerializableAddressBook.java
  src/test/java/peoplesoft/model/AddressBookSerdesTest.java
  src/test/java/peoplesoft/model/job/MoneySerdesTest.java
  src/test/java/peoplesoft/model/job/RateSerdesTest.java
  src/test/java/peoplesoft/model/person/AddressSerdesTest.java
  src/test/java/peoplesoft/model/person/EmailSerdesTest.java
  src/test/java/peoplesoft/model/person/NameSerdesTest.java
  src/test/java/peoplesoft/model/person/PersonSerdesTest.java
  src/test/java/peoplesoft/model/person/PhoneSerdesTest.java
  src/test/java/peoplesoft/model/person/UniquePersonListSerdesTest.java
  src/test/java/peoplesoft/model/tag/TagSerdesTest.java
  src/test/java/peoplesoft/storage/JsonAdaptedPersonTest.java
  src/test/java/peoplesoft/storage/JsonSerializableAddressBookTest.java
  src/test/java/peoplesoft/testutil/PersonUtil.java
  src/test/java/peoplesoft/testutil/TestUtil.java
Labels: priority.High

#81 Add `Job` related commands
  data.example/addressbook.json
  src/main/java/peoplesoft/commons/core/JobIdFactory.java
  src/main/java/peoplesoft/logic/commands/ClearCommand.java
  src/main/java/peoplesoft/logic/commands/DeleteCommand.java
  src/main/java/peoplesoft/logic/commands/EditCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobAddCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobDeleteCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobListCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobMarkCommand.java
  src/main/java/peoplesoft/logic/parser/AddressBookParser.java
  src/main/java/peoplesoft/logic/parser/CliSyntax.java
  src/main/java/peoplesoft/logic/parser/ParserUtil.java
  src/main/java/peoplesoft/logic/parser/job/JobAddCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobAssignCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobDeleteCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobMarkCommandParser.java
  src/main/java/peoplesoft/model/AddressBook.java
  src/main/java/peoplesoft/model/Model.java
  src/main/java/peoplesoft/model/ModelManager.java
  src/main/java/peoplesoft/model/ReadOnlyAddressBook.java
  src/main/java/peoplesoft/model/job/Job.java
  src/main/java/peoplesoft/model/job/JobList.java
  src/main/java/peoplesoft/model/job/JobListManager.java
  src/main/java/peoplesoft/model/job/Rate.java
  src/main/java/peoplesoft/model/job/UniqueJobList.java
  src/main/java/peoplesoft/model/util/Employment.java
  src/test/java/peoplesoft/logic/commands/AddCommandTest.java
  src/test/java/peoplesoft/logic/commands/ModelStub.java
  src/test/java/peoplesoft/logic/commands/job/JobAddCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobAssignCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobDeleteCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobMarkCommandTest.java
  src/test/java/peoplesoft/logic/parser/ParserUtilTest.java
  src/test/java/peoplesoft/logic/parser/job/JobAddCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobAssignCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobDeleteCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobMarkCommandParserTest.java
  src/test/java/peoplesoft/model/AddressBookSerdesTest.java
  src/test/java/peoplesoft/model/AddressBookTest.java
  src/test/java/peoplesoft/model/job/JobTest.java
Labels: priority.High

#84 Update developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#86 Update UG and DG after 2101 feedback
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.Medium

#103 Assign `Rate` attribute to `Person`
  data.example/addressbook.json
  src/main/java/peoplesoft/logic/commands/AddCommand.java
  src/main/java/peoplesoft/logic/commands/EditCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobListCommand.java
  src/main/java/peoplesoft/logic/parser/AddCommandParser.java
  src/main/java/peoplesoft/logic/parser/EditCommandParser.java
  src/main/java/peoplesoft/logic/parser/ParserUtil.java
  src/main/java/peoplesoft/model/job/Rate.java
  src/main/java/peoplesoft/model/person/Person.java
  src/main/java/peoplesoft/model/util/SampleDataUtil.java
  src/test/java/peoplesoft/logic/LogicManagerTest.java
  src/test/java/peoplesoft/logic/commands/CommandTestUtil.java
  src/test/java/peoplesoft/logic/parser/AddCommandParserTest.java
  src/test/java/peoplesoft/model/AddressBookSerdesTest.java
  src/test/java/peoplesoft/model/person/PersonSerdesTest.java
  src/test/java/peoplesoft/model/person/PersonTest.java
  src/test/java/peoplesoft/model/person/UniquePersonListSerdesTest.java
  src/test/java/peoplesoft/testutil/EditPersonDescriptorBuilder.java
  src/test/java/peoplesoft/testutil/PersonBuilder.java
  src/test/java/peoplesoft/testutil/PersonUtil.java
  src/test/java/peoplesoft/testutil/TypicalPersons.java
Labels: priority.High

#106 Updated `Employment` to support many-to-many relationships
  data.example/addressbook.json
  src/main/java/peoplesoft/logic/commands/ClearCommand.java
  src/main/java/peoplesoft/logic/commands/DeleteCommand.java
  src/main/java/peoplesoft/logic/commands/EditCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobDeleteCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobListCommand.java
  src/main/java/peoplesoft/model/AddressBook.java
  src/main/java/peoplesoft/model/employment/Employment.java
  src/main/java/peoplesoft/model/employment/exceptions/DuplicateEmploymentException.java
  src/main/java/peoplesoft/model/employment/exceptions/EmploymentNotFoundException.java
  src/main/java/peoplesoft/model/util/ID.java
  src/test/java/peoplesoft/model/AddressBookSerdesTest.java
  src/test/java/peoplesoft/model/employment/EmploymentTest.java
Labels: priority.High

#109 Update `Job` related commands to use `Index`
  src/main/java/peoplesoft/commons/core/JobIdFactory.java
  src/main/java/peoplesoft/commons/core/Messages.java
  src/main/java/peoplesoft/commons/core/PersonIdFactory.java
  src/main/java/peoplesoft/commons/core/index/Index.java
  src/main/java/peoplesoft/logic/commands/DeleteCommand.java
  src/main/java/peoplesoft/logic/commands/EditCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobAddCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobDeleteCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobFindCommand.java
  src/main/java/peoplesoft/logic/commands/job/JobMarkCommand.java
  src/main/java/peoplesoft/logic/parser/AddressBookParser.java
  src/main/java/peoplesoft/logic/parser/CliSyntax.java
  src/main/java/peoplesoft/logic/parser/FindCommandParser.java
  src/main/java/peoplesoft/logic/parser/ParserUtil.java
  src/main/java/peoplesoft/logic/parser/job/JobAddCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobAssignCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobDeleteCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobFindCommandParser.java
  src/main/java/peoplesoft/logic/parser/job/JobMarkCommandParser.java
  src/main/java/peoplesoft/model/employment/Employment.java
  src/main/java/peoplesoft/model/job/JobContainsKeywordsPredicate.java
  src/test/java/peoplesoft/logic/commands/job/JobAddCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobAssignCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobDeleteCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobFindCommandTest.java
  src/test/java/peoplesoft/logic/commands/job/JobMarkCommandTest.java
  src/test/java/peoplesoft/logic/parser/ParserUtilTest.java
  src/test/java/peoplesoft/logic/parser/job/JobAddCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobAssignCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobDeleteCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobFindCommandParserTest.java
  src/test/java/peoplesoft/logic/parser/job/JobMarkCommandParserTest.java
Labels: priority.High

#136 Update changes to the UG to include `pay`
  docs/UserGuide.md
Labels: priority.High

#135 Small fix for `assign` on marked `Job`s
  src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
  src/main/java/peoplesoft/model/util/SampleDataUtil.java
Labels: priority.Medium, severity.Low
